version: '3.8'
services:

  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    expose:
      - 9092
    environment:
      - KAFKA_CFG_NODE_ID=0
      - KAFKA_CFG_PROCESS_ROLES=controller,broker
      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
    networks:
      - microservices-net


# ---------- User Service Django ----------
  user-service:
    build:
      context: ./UserProj
      dockerfile: Dockerfile
    container_name: user-service
    restart: unless-stopped
    volumes:
      - ./UserProj:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      - kafka
    networks:
      - microservices-net

  user-consumer:
    build:
      context: ./UserProj
    command: python manage.py run_kafka_consumer
    depends_on:
      - kafka
    networks:
      - microservices-net


# ---------- Book Service Django ----------
  book-service:
    build:
      context: ./BookProj
      dockerfile: Dockerfile
    container_name: book-service
    restart: unless-stopped
    volumes:
      - ./BookProj:/app
    environment:
      - KAFKA_BOOTSTRAP_SERVERS=kafka:9092
    ports:
      - "8001:8001"
    depends_on:
      - kafka
    networks:
      - microservices-net

  book-consumer:
    build:
      context: ./BookProj
    command: python manage.py run_kafka_consumer
    depends_on:
      - kafka
    networks:
      - microservices-net


networks:
  microservices-net:
    driver: bridge